replicaCount: 1

postgresql:
  enabled: false
  primary:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  auth:
    postgresPassword: "pedido123"
    username: "pedido"
    password: "pedido123"
    database: "pedidos"

backend:
  image:
    repository: sczyh30/spring-petclinic-rest
    tag: "2.6.0"
    pullPolicy: IfNotPresent
  replicas: 2
  port: 8080
  dbHost: "pedido-app-dev-postgresql"  # ← nombre exacto del service en dev
  dbName: "pedidos"
  dbUser: "pedido"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  image:
    repository: nginx
    tag: "alpine"
    pullPolicy: IfNotPresent
  replicas: 1
  port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

service:
  type: ClusterIP

ingress:
  enabled: true
  className: nginx

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
