# Values por defecto para pedido-app
replicaCount: 1

# PostgreSQL (subchart Bitnami)
postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  auth:
    postgresPassword: pedido123
    username: pedidos_user
    password: userpass123
    database: pedidos

# Backend Spring Boot
backend:
  image:
    repository: juanlacouture/pedido-backend
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 2
  port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Frontend React
frontend:
  image:
    repository: juanlacouture/pedido-frontend
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

# Comunes
service:
  type: ClusterIP
ingress:
  enabled: true
  className: nginx

# HPA Backend
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
