replicaCount: 1

postgresql:
  enabled: false

db:
  username: "pedido"
  password: "pedido123"
  database: "pedidos"
  storage: "8Gi"

backend:
  image:
    repository: springcommunity/spring-petclinic-rest
    tag: "3.0.2"
    pullPolicy: Always
  replicas: 2
  port: 9966          # ← CORREGIDO: era 8080, la app corre en 9966
  dbHost: "pedido-app-dev-postgresql"   # ← CORREGIDO: nombre completo del service
  dbName: "pedidos"
  dbUser: "pedido"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
  readinessProbe:
    httpGet:
      path: /petclinic/api/vets
      port: 9966
    initialDelaySeconds: 180    # ← Spring tarda ~90s solo en contexto
    periodSeconds: 15
    failureThreshold: 5
    timeoutSeconds: 3
  livenessProbe:
    httpGet:
      path: /petclinic/api/vets
      port: 9966
    initialDelaySeconds: 210
    periodSeconds: 20
    failureThreshold: 5
    timeoutSeconds: 3

frontend:
  image:
    repository: nginx
    tag: "alpine"
    pullPolicy: IfNotPresent
  replicas: 1
  port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

service:
  type: ClusterIP

ingress:
  enabled: true
  className: nginx

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70