apiVersion: v1
kind: Service
metadata:
  name: {{ include "pedido-app.fullname" . }}-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
    protocol: TCP
    name: http
  selector:
    app: frontend
