apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pedido-app.fullname" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.port | int }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.port | int }}
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.port | int }}
          initialDelaySeconds: 10
