apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pedido-app.fullname" . }}-db-secret
type: Opaque
data:
  db-password: {{ .Values.db.password | b64enc | quote }}
  db-username: {{ .Values.db.username | b64enc | quote }}
