apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pedido-app.fullname" . }}-db-secret
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
